#!/bin/sh
set -e

echo "⚙ frontend checks…"
cd frontend && npm run type-check && npm run biome:check && npm run build && cd ..

echo "⚙ backend checks…"
cd backend-nest && npm run type-check && npm run biome:check && npm run build && npm run test && cd ..
